project:
  type: book
  output-dir: docs

execute:
  freeze: auto

book:
  title: "Material on Survival Analyses"
  author: "[John Zobolas](https://github.com/bblodfon)"
  date: last-modified
  description: "Various code examples and methodologies for survival analysis"
  repo-url: https://github.com/bblodfon/surv-courses/
  repo-branch: main
  chapters:
    - index.qmd
    - na_km_logrank.qmd
    - cox_regr.qmd
    - cox_regr_high_dim.qmd
    - aalen.qmd
    - mstate.qmd
    - frailty.qmd
    - ncc.qmd
    - point_trts.qmd
    - time_dep_trts.qmd
    - sustained_trts.qmd
    - causal_comp_risk.qmd

format:
  html:
    page-layout: full