<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Various code examples and methodologies for survival analysis">

<title>Material on Survival Analyses - Case-control studies</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./frailty.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ncc.html">Case-control studies</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Material on Survival Analyses</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/bblodfon/surv-courses/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Intro</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./na_km_logrank.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Non-parametric estimators</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cox_regr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cox Regression (low-dim)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cox_regr_high_dim.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cox regression (high-dim)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./aalen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Additive regression</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./mstate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multi-state models</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./frailty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Frailty models for clustered data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ncc.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Case-control studies</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
        
    </div>
<!-- main -->
<main class="content column-page-right" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Case-control studies</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="cell" data-hash="ncc_cache/html/libs_a3b3894cd12ddefea4b6164973270da7">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmnet)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tibble)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In this exercise we will use data from a cohort of <span class="math inline">\(1720\)</span> female patients who were discharged from two tuberculosis sanatoria in Massachusetts between 1930 and 1956 to investigate breast cancer risk of radiation exposure due to fluoroscopy. Radiation doses have been estimated for <span class="math inline">\(1022\)</span> women who received radiation exposure to the chest from X-ray fluoroscopy lung examinations. Some women had multiple exposures to radiation. The remaining <span class="math inline">\(698\)</span> women in the cohort received treatments that did not require fluoroscopic monitoring and were radiation unexposed. The patients had been followed up until the end of 1980, by which time <span class="math inline">\(75\)</span> breast cancer cases were observed. (Source: Hrubec et al., Cancer Research, 1989)</p>
<p>For this cohort radiation data have been collected for all <span class="math inline">\(1720\)</span> women. <strong>But the workload of exposure data collection would have been reduced if the investigators had used a cohort sampling design</strong>. In this exercise we will look at estimation based on the full cohort and for nested case-control and case-cohort samples selected from the full cohort.</p>
<p>We first look at the cohort data. You may read these data into R by the command</p>
<div class="cell" data-hash="ncc_cache/html/unnamed-chunk-1_c569b23fcb13061f26b8d9207fe037ca">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>cohort<span class="ot">=</span><span class="fu">read.table</span>(<span class="st">"https://www.med.uio.no/imb/english/research/centres/ocbe/courses/imb9335/radiationbreast.cohort.txt"</span>, <span class="at">header=</span>T) <span class="sc">%&gt;%</span> <span class="fu">as_tibble</span>()</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>cohort</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,720 × 6
      id   dose number ageentry ageexit status
   &lt;int&gt;  &lt;dbl&gt;  &lt;int&gt;    &lt;dbl&gt;   &lt;dbl&gt;  &lt;int&gt;
 1     1 0           0     14.6    47.4      0
 2     2 0           0     14.2    52.6      0
 3     3 0           0     17.5    69.8      0
 4     4 0           0     14.0    46.3      0
 5     5 0           0     16.5    61.7      0
 6     6 0.0660      4     16.0    58.6      0
 7     7 1.25      108     13.0    62.3      0
 8     8 0           0     13.2    53.5      0
 9     9 0           0     17.3    42.5      1
10    10 0.141      32     19.0    22.6      0
# ℹ 1,710 more rows</code></pre>
</div>
</div>
<p>The data are organized with one line for each of the 1720 women, and with the following variables in the six columns:</p>
<ul>
<li><em>id</em>: subject id</li>
<li><em>dose</em>: radiation dose (Gy)</li>
<li><em>number</em>: number of fluoroscopic examinations</li>
<li><em>ageentry</em>: age at entry into the study (in years)</li>
<li><em>ageexit</em>: age at breast cancer or censoring (in years)</li>
<li><em>status</em>: breast cancer status (0: censored; 1: breast cancer)</li>
</ul>
<p>To model the effect of radiation dose on breast cancer risk, we will consider a Cox regression model with <span class="math inline">\(log2(dose + 1)\)</span>, with dose measured in grays (Gy), as covariate. You may fit this model for cohort data by the commands:</p>
<div class="cell" data-hash="ncc_cache/html/unnamed-chunk-2_95e37755100ac45c968f62ea851dec2f">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>fit.cohort<span class="ot">=</span><span class="fu">coxph</span>(<span class="fu">Surv</span>(ageentry,ageexit,status)<span class="sc">~</span><span class="fu">log2</span>(dose<span class="sc">+</span><span class="dv">1</span>), <span class="at">data=</span>cohort)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit.cohort)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(ageentry, ageexit, status) ~ log2(dose + 
    1), data = cohort)

  n= 1720, number of events= 75 

                 coef exp(coef) se(coef)     z Pr(&gt;|z|)   
log2(dose + 1) 0.4907    1.6335   0.1617 3.035  0.00241 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

               exp(coef) exp(-coef) lower .95 upper .95
log2(dose + 1)     1.634     0.6122      1.19     2.243

Concordance= 0.586  (se = 0.034 )
Likelihood ratio test= 8.64  on 1 df,   p=0.003
Wald test            = 9.21  on 1 df,   p=0.002
Score (logrank) test = 9.44  on 1 df,   p=0.002</code></pre>
</div>
</div>
<p>We then consider nested case-control data with two controls per case <span class="math inline">\((m=2)\)</span>. You may read these data into R by the command</p>
<div class="cell" data-hash="ncc_cache/html/unnamed-chunk-3_7970206654f91532e146091215d4bbbf">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>ncc<span class="ot">=</span><span class="fu">read.table</span>(<span class="st">"https://www.med.uio.no/imb/english/research/centres/ocbe/courses/imb9335/radiationbreast.ncc.txt"</span>, <span class="at">header=</span>T) <span class="sc">%&gt;%</span> <span class="fu">as_tibble</span>()</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>ncc</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 225 × 8
      id  dose number ageentry ageexit status setno  case
   &lt;int&gt; &lt;dbl&gt;  &lt;int&gt;    &lt;dbl&gt;   &lt;dbl&gt;  &lt;int&gt; &lt;int&gt; &lt;int&gt;
 1     9 0          0    17.3     42.5      1     1     1
 2  2717 0          0    31.2     83.2      0     1     0
 3   311 0          0    14.4     61.7      0     1     0
 4    22 0.617     39    17.2     25.4      1     2     1
 5    66 0.259     27    11.5     44.8      0     2     0
 6   401 1.83     111     5.25    51.4      0     2     0
 7    29 0.594     36    17.7     48.5      1     3     1
 8  3027 2.63     267    21.5     73.8      0     3     0
 9  2349 0.807     82    23.4     69.7      0     3     0
10    31 0          0    12.5     36.6      1     4     1
# ℹ 215 more rows</code></pre>
</div>
</div>
<p>The data are organized with three lines for each of the <strong>75 sampled risk sets</strong> (one line for the case, and one line for each of the two controls, randomly selected, but falling within the risk set, e.g.&nbsp;the is an overlap between the age interval - think!), and with eight columns. The first six columns are as for the cohort data, while the variables in the two last columns are:</p>
<ul>
<li><em>case</em>: case-control status within the sampled risk set (0=control, 1=case)</li>
<li><em>setno</em>: label of sampled risk set</li>
</ul>
<p>You may fit the Cox regression model for the nested case-control data by the commands: Note we use <code>case</code> instead of <code>status</code> and <code>strata(setno)</code> so that only the 3 patients per <code>setno</code> are used for the calculation of the risk set:</p>
<div class="cell" data-hash="ncc_cache/html/unnamed-chunk-4_d6dc7a328941319b0e4c58732f3c9600">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>fit.ncc <span class="ot">=</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(ageentry,ageexit,case) <span class="sc">~</span> <span class="fu">log2</span>(dose<span class="sc">+</span><span class="dv">1</span>)<span class="sc">+</span><span class="fu">strata</span>(setno),<span class="at">data=</span>ncc)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit.ncc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
coxph(formula = Surv(ageentry, ageexit, case) ~ log2(dose + 1) + 
    strata(setno), data = ncc)

  n= 225, number of events= 75 

                 coef exp(coef) se(coef)     z Pr(&gt;|z|)  
log2(dose + 1) 0.5404    1.7167   0.2366 2.284   0.0224 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

               exp(coef) exp(-coef) lower .95 upper .95
log2(dose + 1)     1.717     0.5825      1.08      2.73

Concordance= 0.563  (se = 0.058 )
Likelihood ratio test= 5.39  on 1 df,   p=0.02
Wald test            = 5.22  on 1 df,   p=0.02
Score (logrank) test = 5.39  on 1 df,   p=0.02</code></pre>
</div>
</div>
<ol start="2" type="a">
<li>Explain why these commands maximize the partial likelihood for nested case-control data. Perform the commands and compare the result with those you obtained for the cohort data.</li>
</ol>
<p>We then consider case-cohort data with a subcohort of <span class="math inline">\(150\)</span> women. You may read these data into R by the command</p>
<div class="cell" data-hash="ncc_cache/html/unnamed-chunk-5_58e25e6a75b904276b9afc2b26bbf6d9">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>caseco<span class="ot">=</span><span class="fu">read.table</span>(<span class="st">"https://www.med.uio.no/imb/english/research/centres/ocbe/courses/imb9335/radiationbreast.caseco.txt"</span>, <span class="at">header=</span>T) <span class="sc">%&gt;%</span> <span class="fu">as_tibble</span>()</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>caseco</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 218 × 7
      id  dose number ageentry ageexit status  subc
   &lt;int&gt; &lt;dbl&gt;  &lt;int&gt;    &lt;dbl&gt;   &lt;dbl&gt;  &lt;int&gt; &lt;int&gt;
 1  2133 0          0     33.3    68.6      0     1
 2  2608 0.826     84     25.8    67.6      0     1
 3   497 0          0     16.2    60.6      0     1
 4  2658 1.62     193     24.4    63.7      0     1
 5  2611 0          0     24.2    68.5      0     1
 6  3152 0          0     36.5    75.7      0     1
 7   118 0.974     59     16.3    34.2      0     1
 8  3352 0          0     27.9    39.3      1     1
 9  2210 1.51     181     20.8    54.0      0     1
10   165 0.248     15     10.2    19.1      0     1
# ℹ 208 more rows</code></pre>
</div>
</div>
<p>The data are organized with <strong>one line for each woman who is in the subcohort or is a cancer case outside the subcohort</strong> (no censored patients outside the subcohort!). The <span class="math inline">\(150\)</span> women were randomly selected to be in the subcohort. The rest to reach <span class="math inline">\(218\)</span> were the cases added (<span class="math inline">\(status=1\)</span>) that are not in the subcohort. <strong>All the cases (<span class="math inline">\(75\)</span>) are included in the data (as was the case with ncc)</strong>! The data file has seven columns. The first six columns are as for the cohort data, while the last column is:</p>
<ul>
<li><em>subc</em>: subcohort status (0: not in subcohort; 1: member of subcohort)</li>
</ul>
<p>For case cohort-data there are two possible methods of estimation. You may fit the Cox model for the case-cohort data using Prentice’s method by the commands:</p>
<div class="cell" data-hash="ncc_cache/html/unnamed-chunk-6_9c565b38e597f4f31169416300995746">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>fit.prentice <span class="ot">=</span> <span class="fu">cch</span>(<span class="fu">Surv</span>(ageentry,ageexit,status)<span class="sc">~</span> <span class="fu">log2</span>(dose<span class="sc">+</span><span class="dv">1</span>), <span class="at">data=</span>caseco, <span class="at">subcoh=</span><span class="sc">~</span>subc, <span class="at">id=</span><span class="sc">~</span>id, <span class="at">method=</span><span class="st">"Prentice"</span>, <span class="at">cohort.size=</span><span class="dv">1720</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(fit.prentice)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Case-cohort analysis,x$method, Prentice 
 with subcohort of 150 from cohort of 1720 

Call: cch(formula = Surv(ageentry, ageexit, status) ~ log2(dose + 1), 
    data = caseco, subcoh = ~subc, id = ~id, cohort.size = 1720, 
    method = "Prentice")

Coefficients:
         Value        SE        Z          p
[1,] 0.5194255 0.2152382 2.413259 0.01581057</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit.prentice)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Case-cohort analysis,x$method, Prentice 
 with subcohort of 150 from cohort of 1720 

Call: cch(formula = Surv(ageentry, ageexit, status) ~ log2(dose + 1), 
    data = caseco, subcoh = ~subc, id = ~id, cohort.size = 1720, 
    method = "Prentice")

Coefficients:
       Coef    HR  (95%   CI)     p
Value 0.519 1.681 1.102 2.563 0.016</code></pre>
</div>
</div>
<ol start="3" type="a">
<li>Perform the commands and compare the result with those you obtained for cohort data and nested case-control data. Also fit the model using inverse probability weighting (which is achieved by using method=“LinYing”), and compare with the results for Prentice’s method.</li>
</ol>
<div class="cell" data-hash="ncc_cache/html/unnamed-chunk-7_a5c89eeff15b85dca7d3903f88df896c">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>fit.ipw <span class="ot">=</span> survival<span class="sc">::</span><span class="fu">cch</span>(<span class="fu">Surv</span>(ageentry,ageexit,status)<span class="sc">~</span> <span class="fu">log2</span>(dose<span class="sc">+</span><span class="dv">1</span>), <span class="at">data=</span>caseco, <span class="at">subcoh=</span><span class="sc">~</span>subc, <span class="at">id=</span><span class="sc">~</span>id, <span class="at">method=</span><span class="st">"LinYing"</span>, <span class="at">cohort.size=</span><span class="dv">1720</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit.ipw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Case-cohort analysis,x$method, LinYing 
 with subcohort of 150 from cohort of 1720 

Call: survival::cch(formula = Surv(ageentry, ageexit, status) ~ log2(dose + 
    1), data = caseco, subcoh = ~subc, id = ~id, cohort.size = 1720, 
    method = "LinYing")

Coefficients:
       Coef    HR  (95%   CI)     p
Value 0.524 1.688 1.116 2.555 0.013</code></pre>
</div>
</div>
<p>Finally we consider <strong>stratified case-cohort data</strong> where the sub-cohort consists of 50 women selected from each of the three strata:</p>
<ol type="i">
<li><p>women with no fluoroscopic examinations (698 women)</p></li>
<li><p>women with 1-149 fluoroscopic examinations (765 women)</p></li>
<li><p>women with 150 or more fluoroscopic examinations (257 women)</p></li>
</ol>
<p>You may read the stratified case-cohort data into R by the command:</p>
<div class="cell" data-hash="ncc_cache/html/unnamed-chunk-8_affdae74645cc9c3a7acaa9fc966d1d5">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>stratcaseco<span class="ot">=</span><span class="fu">read.table</span>(<span class="st">"https://www.med.uio.no/imb/english/research/centres/ocbe/courses/imb9335/radiationbreast.stratcaseco.txt"</span>, <span class="at">header=</span>T) <span class="sc">%&gt;%</span> <span class="fu">as_tibble</span>()</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>stratcaseco</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 221 × 8
      id  dose number ageentry ageexit status  subc stratum
   &lt;int&gt; &lt;dbl&gt;  &lt;int&gt;    &lt;dbl&gt;   &lt;dbl&gt;  &lt;int&gt; &lt;int&gt;   &lt;int&gt;
 1  2894     0      0     29.3    39.8      0     1       1
 2  2885     0      0     40.6    76.4      0     1       1
 3  2490     0      0     18.3    40.9      0     1       1
 4  2717     0      0     31.2    83.2      0     1       1
 5  3015     0      0     29.7    60.4      0     1       1
 6    73     0      0     16.3    64.6      0     1       1
 7    44     0      0     17.9    19.5      0     1       1
 8  3277     0      0     26.1    70.4      0     1       1
 9  2873     0      0     25.6    62.9      0     1       1
10  2423     0      0     24.8    62.1      0     1       1
# ℹ 211 more rows</code></pre>
</div>
</div>
<p>The data are organized with one line for each woman who is in the subcohort or is a cancer case outside the subcohort. The data file has eight columns. The first six columns are as for the cohort data, while the two last column are</p>
<ul>
<li><em>subc</em>: subcohort status (0: not in subcohrt; 1: member of subcohort)</li>
<li><em>stratum</em>: sampling stratum (1: no fluoroscopic examinations; 2: 1-149 examinations; 3: 150 examinations or more)</li>
</ul>
<p>You may fit the Cox model for the stratified case-cohort data using inverse probability weighting by the commands:</p>
<div class="cell" data-hash="ncc_cache/html/unnamed-chunk-9_21ac3f34186845162492ae47301b8eed">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>stratsize<span class="ot">=</span><span class="fu">c</span>(<span class="dv">698</span>,<span class="dv">765</span>,<span class="dv">257</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(stratsize)<span class="ot">=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>fit.ipw2<span class="ot">=</span><span class="fu">cch</span>(<span class="fu">Surv</span>(ageentry,ageexit,status)<span class="sc">~</span><span class="fu">log2</span>(dose<span class="sc">+</span><span class="dv">1</span>), <span class="at">data=</span>stratcaseco, <span class="at">subcoh=</span><span class="sc">~</span>subc,<span class="at">id=</span><span class="sc">~</span>id, <span class="at">stratum=</span><span class="sc">~</span>stratum, <span class="at">method=</span><span class="st">"II.Borgan"</span>, <span class="at">cohort.size=</span>stratsize)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Borgan II method is a generalization of the Lin-Ying estimator for stratified case-control data</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit.ipw2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Exposure-stratified case-cohort analysis, II.Borgan method.
            1   2   3
subcohort  71  87  63
cohort    698 765 257
Call: cch(formula = Surv(ageentry, ageexit, status) ~ log2(dose + 1), 
    data = stratcaseco, subcoh = ~subc, id = ~id, stratum = ~stratum, 
    cohort.size = stratsize, method = "II.Borgan")

Coefficients:
       Coef    HR  (95%   CI)     p
Value 0.506 1.658 1.157 2.377 0.006</code></pre>
</div>
</div>
<ol start="4" type="a">
<li>Perform the commands and compare the result with those you obtained for case-cohort data with no stratification.</li>
</ol>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation column-page-right">
  <div class="nav-page nav-page-previous">
      <a href="./frailty.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Frailty models for clustered data</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->



</body></html>